export const GET_SUBREDDIT = 'GET_SUBREDDIT'
export const SUBREDDIT_SUCCESS = 'GET_SUBREDDIT_SUCCESS'
export const SUBREDDIT_FAILURE = 'GET_SUBREDDIT_FAILURE'

export const LIKE_POST = 'LIKE_POST'
export const REMOVE_POST = 'REMOVE_POST'

export const GET_SAVED_POSTS = 'GET_SAVED_POSTS'